# Default values for redis-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: redisoperator/operator
  tag: master
  pullPolicy: IfNotPresent
log:
  level: 2
strategy: Recreate
serviceAccount: redis-operator
apiGroupName: redisoperator.k8s.io
broker:
  activate: true
  deployClusterServiceBroker: true
  port: 8080
  # Certificate details to use for TLS. Leave blank to not use TLS
  tls:
    # base-64 encoded PEM data for the TLS certificate
    cert:
    # base-64 encoded PEM data for the private key matching the certificate
    key:
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
