{{- if and .Values.broker.activate (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1") }}
apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: redis-broker
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: redis-broker
  subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{ end }}