apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: 
    type: {{ .Values.strategy }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: "{{ .Values.serviceAccount }}"                  
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
          - "--namespace=$(POD_NAMESPACE)"
          {{- if .Values.broker.activate}}
          - --activate-broker
          - "true"
          - --broker-port
          - "{{ .Values.broker.port }}"
          {{- if .Values.broker.tls.cert}}
          - --tlsCert
          - "{{ .Values.broker.tls.cert }}"
          {{- end}}
          {{- if .Values.broker.tls.key}}
          - --tlsKey
          - "{{ .Values.broker.tls.key }}"
          {{- end}}
          {{- end}}
          - -v
          - "{{ .Values.log.level }}"
          - --logtostderr
          - --alsologtostderr
          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 5
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
