{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    name: {{ template "serviceaccount" . }}
  rules:
  - apiGroups: [""]
    resources:
    - namespaces
    - services
    - endpoints
    - pods
    verbs: ["list", "get"]
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: {{ template "serviceaccount" . }}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ template "serviceaccount" . }}
  subjects:
  - kind: ServiceAccount
    name: {{ template "serviceaccount" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}